version: '2'
services:
  bootnode-1:
    build:
      context: .
      dockerfile: ./gur-client/Dockerfile
    # restart: on-failure
    hostname: bootnode-1
    command: ./bootnode.sh
    volumes:
      - ./files/bootnode.sh:/home/deploy/bootnode.sh
      - ./files/attach.sh:/home/deploy/attach.sh
      - ./files/gur-options.sh:/home/deploy/gur-options.sh
      - /etc/localtime:/etc/localtime:ro

  bootnode-2:
    build:
      context: .
      dockerfile: ./gur-client/Dockerfile
    # restart: on-failure
    hostname: bootnode-2
    command: ./bootnode.sh
    volumes:
      - ./files/bootnode.sh:/home/deploy/bootnode.sh
      - ./files/attach.sh:/home/deploy/attach.sh
      - ./files/gur-options.sh:/home/deploy/gur-options.sh
      - /etc/localtime:/etc/localtime:ro

  rpc-1:
    build:
      context: .
      dockerfile: ./gur-client/Dockerfile
    # restart: on-failure
    command: ./rpc.sh
    volumes:
      - ./files/rpc.sh:/home/deploy/rpc.sh
      - ./files/attach.sh:/home/deploy/attach.sh
      - ./files/gur-options.sh:/home/deploy/gur-options.sh
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9595:9595"
    depends_on:
      - bootnode-1
      - bootnode-2

  miner-1:
    build:
      context: .
      dockerfile: ./gur-client/Dockerfile
    # restart: on-failure
    command: ./miner.sh
    volumes:
      # - ethash:/home/deploy/.ethash
      - ./files/miner.sh:/home/deploy/miner.sh
      - ./files/start-mining.sh:/home/deploy/start-mining.sh
      - ./files/stop-mining.sh:/home/deploy/stop-mining.sh
      - ./files/attach.sh:/home/deploy/attach.sh
      - ./files/gur-options.sh:/home/deploy/gur-options.sh
      - ./files/password:/home/deploy/files/password:ro
      - ./files/keystore:/home/deploy/ur_data/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - bootnode-1
      - bootnode-2

  explorer-1:
    build:
      context: .
      dockerfile: ./gur-explorer/Dockerfile
    # restart: on-failure
    command: ./explorer.sh
    volumes:
      - ./files/explorer.sh:/home/deploy/explorer.sh
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080"
    depends_on:
      - rpc-1

# volumes:
#     ethash:
#       driver: local
