version: '2'
services:
  identifier-1:
    extra_hosts:
      - "bootnode-1:10.134.9.248"
      - "bootnode-2:10.134.10.242"
      - "explorer-1:10.134.11.100"
      - "miner-1:10.134.11.120"
      - "queue-processor-1:10.134.11.121"
      - "transaction-relay-1:10.134.11.121"
    container_name: identifier-1
    hostname: identifier-1
    build:
      context: .
      dockerfile: ./identifier.dockerfile
    # restart: on-failure
    command: /bin/bash
    volumes:
      - ./files:/home/deploy/files
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080"
