version: '2'
services:
  bootnode-1:
    container_name: bootnode-1
    hostname: bootnode-1
    build:
      context: .
      dockerfile: ./gur.dockerfile
    environment:
      - UR_ENV=${UR_ENV}
      - UR_NETWORK_ID=${UR_NETWORK_ID}
      - BOOTNODE_1_PUBLIC_IP=${BOOTNODE_1_PUBLIC_IP}
      - BOOTNODE_2_PUBLIC_IP=${BOOTNODE_2_PUBLIC_IP}
      - EXPLORER_1_PUBLIC_IP=${EXPLORER_1_PUBLIC_IP}
    command: files/bootnode.sh
    volumes:
      - ./files:/home/deploy/files
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "19595:19595"
      - "19595:19595/udp"

  bootnode-2:
    container_name: bootnode-2
    hostname: bootnode-2
    build:
      context: .
      dockerfile: ./gur.dockerfile
    environment:
      - UR_ENV=${UR_ENV}
      - UR_NETWORK_ID=${UR_NETWORK_ID}
      - BOOTNODE_1_PUBLIC_IP=${BOOTNODE_1_PUBLIC_IP}
      - BOOTNODE_2_PUBLIC_IP=${BOOTNODE_2_PUBLIC_IP}
      - EXPLORER_1_PUBLIC_IP=${EXPLORER_1_PUBLIC_IP}
    command: files/bootnode.sh
    volumes:
      - ./files:/home/deploy/files
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "19595:19595"
      - "19595:19595/udp"

  explorer-1:
    container_name: explorer-1
    hostname: explorer-1
    build:
      context: .
      dockerfile: ./explorer.dockerfile
    environment:
      - UR_ENV=${UR_ENV}
      - UR_NETWORK_ID=${UR_NETWORK_ID}
      - BOOTNODE_1_PUBLIC_IP=${BOOTNODE_1_PUBLIC_IP}
      - BOOTNODE_2_PUBLIC_IP=${BOOTNODE_2_PUBLIC_IP}
      - EXPLORER_1_PUBLIC_IP=${EXPLORER_1_PUBLIC_IP}
    command: files/explorer.sh
    volumes:
      - ./files:/home/deploy/files
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:8080"
      - "9595:9595"

  miner-1:
    container_name: miner-1
    hostname: miner-1
    build:
      context: .
      dockerfile: ./gur.dockerfile
    environment:
      - UR_ENV=${UR_ENV}
      - UR_NETWORK_ID=${UR_NETWORK_ID}
      - BOOTNODE_1_PUBLIC_IP=${BOOTNODE_1_PUBLIC_IP}
      - BOOTNODE_2_PUBLIC_IP=${BOOTNODE_2_PUBLIC_IP}
      - EXPLORER_1_PUBLIC_IP=${EXPLORER_1_PUBLIC_IP}
    command: files/miner.sh
    volumes:
      # - ethash:/home/deploy/.ethash
      - ./files:/home/deploy/files
      - /etc/localtime:/etc/localtime:ro

  transaction-relay-1:
    container_name: transaction-relay-1
    hostname: transaction-relay-1
    build:
      context: .
      dockerfile: ./gur.dockerfile
    environment:
      - UR_ENV=${UR_ENV}
      - UR_NETWORK_ID=${UR_NETWORK_ID}
      - BOOTNODE_1_PUBLIC_IP=${BOOTNODE_1_PUBLIC_IP}
      - BOOTNODE_2_PUBLIC_IP=${BOOTNODE_2_PUBLIC_IP}
      - EXPLORER_1_PUBLIC_IP=${EXPLORER_1_PUBLIC_IP}
    command: files/transaction-relay.sh
    volumes:
      - ./files:/home/deploy/files
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9595:9595"
      - "19595:19595"
      - "19595:19595/udp"

  identifier-1:
    container_name: identifier-1
    hostname: identifier-1
    build:
      context: .
      dockerfile: ./identifier.dockerfile
    environment:
      - UR_ENV=${UR_ENV}
      - UR_NETWORK_ID=${UR_NETWORK_ID}
      - BOOTNODE_1_PUBLIC_IP=${BOOTNODE_1_PUBLIC_IP}
      - BOOTNODE_2_PUBLIC_IP=${BOOTNODE_2_PUBLIC_IP}
      - PRIVILEGED_UTI_OUTBOUND_PASSWORD=${PRIVILEGED_UTI_OUTBOUND_PASSWORD}
    command: files/identifier.sh
    volumes:
      - ./files:/home/deploy/files
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - "8080:8080"
    #   - "5858:5858"
