version: '2'
services:
  explorer-1:
    extra_hosts:
      - "bootnode-1:10.134.9.248"
      - "bootnode-2:10.134.10.242"
      - "explorer-1:10.134.11.100"
      - "identifier-1:10.134.22.110"
      - "miner-1:10.134.11.120"
      - "rpc-1:10.134.11.121"
    container_name: explorer-1
    hostname: explorer-1
    build:
      context: .
      dockerfile: ./gur-explorer/Dockerfile
    # restart: on-failure
    command: ./explorer.sh
    volumes:
      - ./files/explorer.sh:/home/deploy/explorer.sh
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080"
