version: '2'
services:
  miner:
    extra_hosts:
      - "transaction-relay-1:10.134.11.121"
      - "miner-1:10.134.11.120"
      - "explorer:10.134.11.100"
      - "bootnode2:10.134.10.242"
      - "bootnode1:10.134.9.248"
    container_name: miner
    build:
      context: .
      dockerfile: ./gur-client/Dockerfile
    # restart: on-failure
    command: ./miner.sh
    volumes:
      # - ethash:/home/deploy/.ethash
      - ./files/miner.sh:/home/deploy/miner.sh
      - ./files/start-mining.sh:/home/deploy/start-mining.sh
      - ./files/stop-mining.sh:/home/deploy/stop-mining.sh
      - ./files/attach.sh:/home/deploy/attach.sh
      - ./files/params.sh:/home/deploy/params.sh
      - ./files/password:/home/deploy/files/password:ro
      - ./files/keystore:/home/deploy/ur_data/keystore:rw
      - /etc/localtime:/etc/localtime:ro
