version: '2'
services:
  bootnode-2:
    extra_hosts:
      - "bootnode-2:10.134.9.248"
      - "bootnode-2:10.134.10.242"
      - "explorer-2:10.134.11.100"
      - "miner-2:10.134.11.120"
      - "queue-processor-2:10.134.11.121"
      - "transaction-relay-2:10.134.11.121"
    container_name: bootnode-2
    hostname: bootnode-2
    build:
      context: .
      dockerfile: ./gur.dockerfile
    # restart: on-failure
    command: files/bootnode.sh
    volumes:
      - ./files:/home/deploy/files
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "19595:19595"
      - "19595:19595/udp"
