version: '2'
services:
  bootnode1:
    extra_hosts:
      - "transaction-relay-1:10.134.11.121"
      - "miner-1:10.134.11.120"
      - "explorer:10.134.11.100"
      - "bootnode2:10.134.10.242"
      - "bootnode1:10.134.9.248"
    container_name: bootnode1
    build:
      context: .
      dockerfile: ./gur-client/Dockerfile
    # restart: on-failure
    hostname: bootnode1
    command: ./bootnode1.sh
    volumes:
      - ./files/bootnode1.sh:/home/deploy/bootnode1.sh
      - ./files/attach.sh:/home/deploy/attach.sh
      - ./files/params.sh:/home/deploy/params.sh
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "19595:19595"
      - "19595:19595/udp"

