version: '2'
services:
  bootnode-1:
    extra_hosts:
      - "bootnode-1:10.137.16.84"
      - "bootnode-2:10.137.16.222"
      - "explorer-1:10.137.128.189"
      - "miner-1:10.137.16.122"
      - "transaction-relay-1:10.137.144.3"
    container_name: bootnode-1
    hostname: bootnode-1
    build:
      context: .
      dockerfile: ./gur.dockerfile
    # restart: on-failure
    command: files/bootnode.sh
    volumes:
      - ./files:/home/deploy/files
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "19595:19595"
      - "19595:19595/udp"

  bootnode-2:
    extra_hosts:
      - "bootnode-1:10.137.16.84"
      - "bootnode-2:10.137.16.222"
      - "explorer-1:10.137.128.189"
      - "miner-1:10.137.16.122"
      - "transaction-relay-1:10.137.144.3"
    container_name: bootnode-2
    hostname: bootnode-2
    build:
      context: .
      dockerfile: ./gur.dockerfile
    # restart: on-failure
    command: files/bootnode.sh
    volumes:
      - ./files:/home/deploy/files
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "19595:19595"
      - "19595:19595/udp"

  explorer-1:
    extra_hosts:
      - "bootnode-1:10.137.16.84"
      - "bootnode-2:10.137.16.222"
      - "explorer-1:10.137.128.189"
      - "miner-1:10.137.16.122"
      - "transaction-relay-1:10.137.144.3"
    container_name: explorer-1
    hostname: explorer-1
    build:
      context: .
      dockerfile: ./gur-explorer/Dockerfile
    # restart: on-failure
    command: files/explorer.sh
    volumes:
      - ./files:/home/deploy/files
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:8080"
      - "9595:9595"

  miner-1:
    extra_hosts:
      - "bootnode-1:10.137.16.84"
      - "bootnode-2:10.137.16.222"
      - "explorer-1:10.137.128.189"
      - "miner-1:10.137.16.122"
      - "transaction-relay-1:10.137.144.3"
    container_name: miner-1
    hostname: miner-1
    build:
      context: .
      dockerfile: ./gur.dockerfile
    # restart: on-failure
    command: ./miner.sh
    volumes:
      # - ethash:/home/deploy/.ethash
      - ./files:/home/deploy/files
      - /etc/localtime:/etc/localtime:ro

  transaction-relay-1:
    extra_hosts:
      - "bootnode-1:10.137.16.84"
      - "bootnode-2:10.137.16.222"
      - "explorer-1:10.137.128.189"
      - "miner-1:10.137.16.122"
      - "transaction-relay-1:10.137.144.3"
    container_name: transaction-relay-1
    hostname: transaction-relay-1
    build:
      context: .
      dockerfile: ./gur.dockerfile
    # restart: on-failure
    command: files/transaction-relay.sh
    volumes:
      - ./files:/home/deploy/files
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9595:9595"
      - "19595:19595"
      - "19595:19595/udp"

  identifier-1:
    container_name: identifier-1
    hostname: identifier-1
    build:
      context: .
      dockerfile: ./identifier.dockerfile
    # restart: on-failure
    command: ./files/identifier.sh
    volumes:
      - ./files:/home/deploy/files
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - "8080:8080"
    #   - "5858:5858"
