version: '2'
services:
  explorer-1:
    extra_hosts:
      - "bootnode-1:10.134.9.248"
      - "bootnode-2:10.134.10.242"
      - "explorer-1:10.134.11.100"
      - "miner-1:10.134.11.120"
      - "queue-processor-1:10.134.11.121"
      - "transaction-relay-1:10.134.11.121"
    container_name: explorer-1
    hostname: explorer-1
    build:
      context: .
      dockerfile: ./gur-explorer/Dockerfile
    # restart: on-failure
    command: files/explorer.sh
    volumes:
      - ./files:/home/deploy/files
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:8080"
      - "9595:9595"
