version: '2'
services:
  bootnode1:
    build:
      context: .
      dockerfile: ./gur-client/Dockerfile
    # restart: on-failure
    hostname: bootnode1
    command: ./bootnode1.sh
    volumes:
      - ./files/bootnode1.sh:/home/deploy/bootnode1.sh
      - ./files/attach.sh:/home/deploy/attach.sh
      - ./files/params.sh:/home/deploy/params.sh
      - /etc/localtime:/etc/localtime:ro

  bootnode2:
    build:
      context: .
      dockerfile: ./gur-client/Dockerfile
    # restart: on-failure
    hostname: bootnode2
    command: ./bootnode2.sh
    volumes:
      - ./files/bootnode2.sh:/home/deploy/bootnode2.sh
      - ./files/attach.sh:/home/deploy/attach.sh
      - ./files/params.sh:/home/deploy/params.sh
      - /etc/localtime:/etc/localtime:ro

  transaction-relay:
    build:
      context: .
      dockerfile: ./gur-client/Dockerfile
    # restart: on-failure
    command: ./transaction-relay.sh
    volumes:
      - ./files/transaction-relay.sh:/home/deploy/transaction-relay.sh
      - ./files/attach.sh:/home/deploy/attach.sh
      - ./files/params.sh:/home/deploy/params.sh
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9595:9595"
    depends_on:
      - bootnode1
      - bootnode2

  miner:
    build:
      context: .
      dockerfile: ./gur-client/Dockerfile
    # restart: on-failure
    command: ./miner.sh
    volumes:
      # - ethash:/home/deploy/.ethash
      - ./files/miner.sh:/home/deploy/miner.sh
      - ./files/start-mining.sh:/home/deploy/start-mining.sh
      - ./files/stop-mining.sh:/home/deploy/stop-mining.sh
      - ./files/attach.sh:/home/deploy/attach.sh
      - ./files/params.sh:/home/deploy/params.sh
      - ./files/password:/home/deploy/files/password:ro
      - ./files/keystore:/home/deploy/ur_data/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - bootnode1
      - bootnode2

  explorer:
    build:
      context: .
      dockerfile: ./gur-explorer/Dockerfile
    # restart: on-failure
    command: ./explorer.sh
    volumes:
      - ./files/explorer.sh:/home/deploy/explorer.sh
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080"
    depends_on:
      - transaction-relay

# volumes:
#     ethash:
#       driver: local
