version: '2'
services:
  bootnode1:
    build:
      context: .
      dockerfile: ./gur-client/Dockerfile
    # restart: on-failure
    command: ./bootnode1.sh
    volumes:
      - ./files/bootnode1.sh:/root/bootnode1.sh
      - ./files/attach.sh:/root/attach.sh
      - ./files/params.sh:/root/params.sh
      - /etc/localtime:/etc/localtime:ro
  #
  # bootnode2:
  #   build:
  #     context: .
  #     dockerfile: ./gur-client/Dockerfile
  #   # restart: on-failure
  #   command: ./bootnode2.sh
  #   volumes:
  #     - ./files/bootnode2.sh:/root/bootnode2.sh
  #     - ./files/attach.sh:/root/attach.sh
  #     - ./files/params.sh:/root/params.sh
  #     - /etc/localtime:/etc/localtime:ro
  #
  # transaction-relay:
  #   build:
  #     context: .
  #     dockerfile: ./gur-client/Dockerfile
  #   # restart: on-failure
  #   command: ./transaction-relay.sh
  #   volumes:
  #     - ./files/transaction-relay.sh:/root/transaction-relay.sh
  #     - ./files/attach.sh:/root/attach.sh
  #     - ./files/params.sh:/root/params.sh
  #     - /etc/localtime:/etc/localtime:ro
  #   ports:
  #     - "9595"
  #
  # miner:
  #   build:
  #     context: .
  #     dockerfile: ./gur-client/Dockerfile
  #   # restart: on-failure
  #   command: ./miner.sh
  #   volumes:
  #     - ethash:/root/.ethash
  #     - ./files/miner.sh:/root/miner.sh
  #     - ./files/attach.sh:/root/attach.sh
  #     - ./files/params.sh:/root/params.sh
  #     - ./files/password:/root/files/password:ro
  #     - ./files/keystore:/root/ur_data/keystore:rw
  #     - /etc/localtime:/etc/localtime:ro

  explorer:
    build:
      context: .
      dockerfile: ./gur-explorer/Dockerfile
    # restart: on-failure
    command: ./explorer.sh
    volumes:
      - ethash:/root/.ethash
      - ./files/explorer.sh:/root/explorer.sh
      - ./files/attach.sh:/root/attach.sh
      - ./files/params.sh:/root/params.sh
      - ./files/password:/root/files/password:ro
      - ./files/keystore:/root/ur_data/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080"

volumes:
    ethash:
      driver: local
