version: '2'
services:
  transaction-relay:
    extra_hosts:
      - "transaction-relay-1:10.134.11.121"
      - "miner-1:10.134.11.120"
      - "explorer:10.134.11.100"
      - "bootnode2:10.134.10.242"
      - "bootnode1:10.134.9.248"
    container_name: transaction-relay
    build:
      context: .
      dockerfile: ./gur-client/Dockerfile
    # restart: on-failure
    command: ./transaction-relay.sh
    volumes:
      - ./files/transaction-relay.sh:/home/deploy/transaction-relay.sh
      - ./files/attach.sh:/home/deploy/attach.sh
      - ./files/params.sh:/home/deploy/params.sh
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9595:9595"
    depends_on:
      - bootnode1
      - bootnode2
